# Generated by Django 3.2.8 on 2021-10-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_auto_20211018_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
