# Generated by Django 3.2.8 on 2021-10-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_auto_20211019_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={},
        ),
        migrations.RemoveField(
            model_name='notes',
            name='title',
        ),
    ]
