# Generated by Django 3.2.8 on 2021-10-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_auto_20211019_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
