# Generated by Django 3.2.8 on 2021-10-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_auto_20211019_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
