# Generated by Django 3.2.8 on 2021-10-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_auto_20211020_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
